apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-sfsjizgl
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-sfsjizgl:482ce32e56be44c74bcd91e6a091c038d6284062@sha256:f2e85f3971c63cad0f01855fa0c8c6425b8b70987dcbb59be018006192befc5e
          name: container-image
